# Generated by Django 2.0 on 2018-02-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Address',
            new_name='Mailing_Address',
        ),
        migrations.RemoveField(
            model_name='question',
            name='For_Hire',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Priv_Pass',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Priv_Pass_Non',
        ),
        migrations.AddField(
            model_name='question',
            name='Auth_For_Hire',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='City',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='DBA_Name',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='DUNSNumber',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='Granite',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='MCMXFFNumber',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='MCS150',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='Out_Of_Service_Date',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='Physical_adress',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='Priv_Pass_Business',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='Priv_Pass_Non_Business',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='State',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='question',
            name='StateCarrierIDNumber',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='US_Mail_Cargo',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='ZipCode',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='mCity',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='mState',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='question',
            name='mZipCode',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='AgriculturalFarm_Supplies',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Beverages',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Building_Materials',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Chemicals',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='CoalCoke',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Commodities_Dry_Bulk',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Construction',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='DOT_Number',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='DriveTow_away',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Drivers',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='Entity_Type',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Exempt_For_Hire',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Fed_Gov',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Fresh_Produce',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='GarbageRefuse',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='General_Freight',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Grain_Feed_Hay',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Household_Goods',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Indian_Nation',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Intermodal_Cont',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Interstate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Intrastate_NonHM',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Intrastate_Only_HM',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Legal_Name',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='LiquidsGases',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Livestock',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Local_Gov',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Logs_Poles_Beams_Lumber',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Machinery_Large_Objects',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Meat',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Metal_sheets_coils_rolls',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Migrant',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Mileage',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Mobile_Homes',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Motor_Vehicles',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Oilfield_Equipment',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Operating_Status',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Paper_Products',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Passengers',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Phone',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='Private_Property',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Refrigerated_Food',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='State_Gov',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='US_Mail',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Units',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='Utilities',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='Water_Well',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
