# Generated by Django 2.0 on 2018-02-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0003_auto_20180215_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='adress',
            new_name='Physical_adress',
        ),
    ]
