# Generated by Django 2.0 on 2018-02-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0004_auto_20180215_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Drivers',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='Units',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
