# Generated by Django 2.0 on 2018-02-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0005_auto_20180215_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Drivers',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Units',
            field=models.IntegerField(default='0'),
        ),
    ]
